language: r
cache: packages

matrix:
  include:
  - r: devel
  - r: release

env:
  global:
#  - _R_CHECK_FORCE_SUGGESTS_=false
  - _R_CHECK_FORCE_SUGGESTS_=true

# various additional packages needed
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev
      - rustc
      - cargo

before_script:
  # turn on MS core fonts
  - echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
  - sudo apt-get install ttf-mscorefonts-installer
  - sudo fc-cache
