language: r
cache: packages

matrix:
  include:
  - r: devel
  - r: release

env:
  global:
#  - _R_CHECK_FORCE_SUGGESTS_=false
  - _R_CHECK_FORCE_SUGGESTS_=true

# various additional packages needed
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev
      - rustc
      - cargo
      - ttf-mscorefonts-installer

before_script:
  # turn on MS core fonts
  - sudo fc-cache
