---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# gridtext rewrite

An attempt to rewrite the gridtext package from scratch, with all the heavy lifting implemented in Rust.

An initial rendering engine has been implemented, though it is for demonstration purposes only at this time:

```{r}
library(grdtext)
library(grid)

css <-
'.brown { color:red; font-family: "Comic Sans MS"; }
em { color:green; }
strong em { color:blue; font-family: monospace; }
strong .brown { color:brown; font-size: 24px; }'

mdtext <-
'The **quick <span class="brown">brown</span>
*fox*** jumps *over* the <span style="color:#0000ff80">lazy
dog.</span><br>The quick <span class="brown">brown</span> fox.'

g <- render_markdown(mdtext, css)
grid.newpage()
grid.draw(g)
```

Simple markdown-to-html conversion is also implemented:
```{r}
md_to_html("This is *a* **test**.")
```